export default [
  {
    id: 1,
    title: '1984',
    author: 'George Orwell',
    description: 'A dystopian social science fiction novel about the dangers of totalitarianism.',
    rating: 5,
    image: '/1984.jpg',
    category: 'Fiction',
  },
  {
    id: 2,
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    description: 'A novel about the serious issues of rape and racial inequality through the eyes of Scout Finch.',
    rating: 5,
    image: '/mockingbird.jpg',
    category: 'Fiction',
  },
  {
    id: 3,
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    description: 'A novel about the decline of the American Dream in the 1920s.',
    rating: 4,
    image: '/gatsby.jpg',
    category: 'Sci-Fi',
  },
  {
    id: 4,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    description: 'A romantic novel that charts the emotional development of Elizabeth Bennet.',
    rating: 5,
    image: '/pride.jpg',
    category: 'Non-Fiction',
  },
  {
    id: 5,
    title: 'Moby-Dick',
    author: 'Herman Melville',
    description: 'A novel about the voyage of the whaling ship Pequod and the obsession of Captain Ahab.',
    rating: 4,
    image: '/mobydick.jpg',
    category: 'Fiction',
  },
  {
    id: 6,
    title: 'War and Peace',
    author: 'Leo Tolstoy',
    description: 'A novel that chronicles the history of Russia during the Napoleonic Era.',
    rating: 5,
    image: '/warpeace.jpg',
    category: 'Fiction',
  },
  {
    id: 7,
    title: 'The Catcher in the Rye',
    author: 'J.D. Salinger',
    description: 'The experiences of a young man in New York City, struggling with identity and belonging.',
    rating: 4,
    image: '/catcher.jpg',
    category: 'Fiction',
  },
  {
    id: 8,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    description: 'A fantasy novel following the quest of Bilbo Baggins to win a share of treasure guarded by a dragon.',
    rating: 5,
    image: '/hobbit.jpg',
    category: 'Fantasy',
  }
];
